best_epoch: 48
device: cuda
model_id: cnn_lstm_rul_cmapss_fd003
n_features: 14
pytorch_version: !!python/object/new:torch.torch_version.TorchVersion
- 2.6.0+cu124
rul_cap: 130
sensor_indices:
- 2
- 3
- 4
- 7
- 8
- 9
- 11
- 12
- 13
- 14
- 15
- 17
- 20
- 21
seq_len: 50
subset: FD003
test_mae: 15.9
test_nasa_score: 22.0
test_rmse: 22.0
val_rmse: 17.9
